# Generated by Django 3.2.3 on 2021-06-27 09:02

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='memes/default.jpg', upload_to=post.models.upload_to, verbose_name='Meme'),
        ),
    ]
